#
# TABLE STRUCTURE FOR: customer_service
#

DROP TABLE IF EXISTS `customer_service`;

CREATE TABLE `customer_service` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `firstname` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `lastname` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `email` varchar(120) COLLATE utf8_unicode_ci NOT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('1', 'Hudson', 'Crona', 'wunsch.coby@shop.com', '2017-06-30 10:52:43', '2008-10-25 10:23:49');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('2', 'Adriana', 'Dare', 'deven.douglas@shop.com', '2001-09-30 14:59:54', '2003-01-12 05:47:08');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('3', 'Myrtie', 'Schroeder', 'asa.mckenzie@shop.com', '2000-08-30 03:59:18', '1989-12-01 20:46:51');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('4', 'Misael', 'Boyle', 'chanelle.upton@shop.com', '2006-12-01 16:58:56', '1974-09-28 04:52:49');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('5', 'Brayan', 'Quigley', 'constantin73@shop.com', '1995-10-16 09:01:18', '1995-02-18 14:10:39');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('6', 'Harmony', 'Welch', 'ladarius31@shop.com', '1974-04-28 04:28:39', '2001-03-18 19:13:24');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('7', 'Jennifer', 'Kerluke', 'tbrekke@shop.com', '1988-06-08 18:35:38', '2006-02-20 21:55:02');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('8', 'Ally', 'Wisoky', 'freddie72@shop.com', '2000-03-24 10:08:41', '2004-07-15 00:05:51');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('9', 'Monty', 'Marks', 'langworth.dexter@shop.com', '1987-08-27 15:55:15', '2000-09-04 14:15:52');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('10', 'Gregg', 'Tremblay', 'ccarroll@shop.com', '2017-03-27 09:13:35', '1988-12-04 02:10:19');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('11', 'Bernardo', 'Bode', 'vwalker@shop.com', '1978-07-15 23:01:34', '1988-05-26 22:32:50');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('12', 'Brice', 'Bradtke', 'oberbrunner.harmon@shop.com', '2011-04-22 02:07:16', '1999-05-28 15:09:36');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('13', 'Ebba', 'Von', 'rdooley@shop.com', '1999-02-24 02:59:45', '1970-11-12 20:39:55');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('14', 'Vicenta', 'Zboncak', 'dean.flatley@shop.com', '1986-02-23 21:33:16', '2014-02-11 11:43:59');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('15', 'Savanah', 'Runolfsdottir', 'schmeler.clark@shop.com', '1975-10-19 10:05:44', '1973-09-16 21:51:52');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('16', 'Antwon', 'Powlowski', 'ozella.veum@shop.com', '1986-09-18 07:05:44', '2004-03-25 10:54:35');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('17', 'Kellen', 'Hegmann', 'ghuel@shop.com', '1975-01-23 01:27:27', '1996-12-15 13:27:45');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('18', 'Francesco', 'Mitchell', 'owunsch@shop.com', '1999-08-12 22:31:19', '1993-08-07 03:42:57');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('19', 'Ava', 'Runte', 'alisa89@shop.com', '2005-09-19 19:16:29', '2013-09-10 02:54:50');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('20', 'Priscilla', 'Grimes', 'mclaughlin.kyle@shop.com', '2018-07-19 22:33:33', '2015-09-07 23:20:24');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('21', 'Frederique', 'Jones', 'heidi.bogan@shop.com', '2012-11-01 09:48:30', '1989-05-01 20:38:35');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('22', 'Isabell', 'Johnston', 'gertrude95@shop.com', '2001-01-05 14:14:45', '2008-12-13 04:48:49');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('23', 'Tod', 'Jaskolski', 'oblick@shop.com', '1989-01-13 11:29:01', '2007-05-22 00:31:05');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('24', 'Leonora', 'Littel', 'rachelle75@shop.com', '1999-01-05 22:33:43', '1988-06-03 10:09:17');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('25', 'Jevon', 'Stehr', 'wehner.jameson@shop.com', '2007-10-18 17:50:27', '2001-05-13 03:03:12');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('26', 'Elmira', 'Walter', 'herman47@shop.com', '1977-04-20 22:25:33', '2009-05-12 07:02:34');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('27', 'Katrina', 'Yost', 'maye84@shop.com', '1998-09-06 03:04:26', '1989-03-09 06:40:20');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('28', 'Devan', 'Streich', 'jaime54@shop.com', '1990-07-01 14:04:20', '1985-10-22 01:28:47');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('29', 'Eddie', 'Mraz', 'emery.jacobs@shop.com', '1988-10-01 07:00:34', '1972-07-13 18:09:18');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('30', 'Geraldine', 'Renner', 'wilkinson.savion@shop.com', '1973-07-25 08:12:54', '2017-12-24 18:44:01');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('31', 'Cheyanne', 'Mueller', 'wunsch.urban@shop.com', '2012-08-04 18:43:37', '2018-06-15 06:51:08');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('32', 'Anibal', 'Cassin', 'pink.gleason@shop.com', '2016-08-05 14:48:12', '2001-07-19 08:29:53');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('33', 'Ethan', 'Robel', 'kianna84@shop.com', '1999-12-29 06:37:40', '1998-03-04 17:19:10');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('34', 'Scotty', 'Effertz', 'huel.queen@shop.com', '2015-09-18 02:43:29', '1994-06-11 17:22:55');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('35', 'Frida', 'Nienow', 'bayer.jessyca@shop.com', '1988-08-14 06:52:34', '2013-10-09 15:25:36');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('36', 'Abbigail', 'Crooks', 'funk.nora@shop.com', '1991-02-06 06:26:34', '1975-04-07 21:22:07');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('37', 'Rosemarie', 'Leuschke', 'hans61@shop.com', '1974-10-28 13:49:09', '1995-07-21 03:13:55');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('38', 'Brooke', 'Schuppe', 'roger76@shop.com', '1972-04-03 09:12:07', '1983-05-31 15:09:44');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('39', 'Merlin', 'Turner', 'terry.christop@shop.com', '1973-09-23 13:24:56', '2005-01-22 10:26:27');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('40', 'Melany', 'Larkin', 'gladyce.hayes@shop.com', '2011-06-08 20:58:53', '1970-03-21 21:51:22');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('41', 'Verdie', 'McCullough', 'lubowitz.juston@shop.com', '2017-11-11 03:45:45', '1985-01-26 22:19:03');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('42', 'Missouri', 'Berge', 'lhalvorson@shop.com', '1983-01-23 05:26:13', '1993-06-06 09:06:43');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('43', 'Ayana', 'Collins', 'keara.marks@shop.com', '1977-03-07 08:21:19', '1990-08-05 22:54:19');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('44', 'Laurence', 'Ratke', 'conn.raoul@shop.com', '2018-06-22 06:22:14', '1999-03-01 16:06:20');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('45', 'Granville', 'Harris', 'nleffler@shop.com', '1991-07-04 09:47:56', '2000-02-25 21:00:32');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('46', 'Holly', 'Collins', 'hziemann@shop.com', '1986-08-22 05:18:46', '2003-07-06 15:02:49');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('47', 'Keara', 'Gaylord', 'kaya39@shop.com', '1990-11-21 12:01:53', '1973-08-27 00:12:22');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('48', 'Rahsaan', 'Ziemann', 'monroe14@shop.com', '2007-07-12 04:55:52', '1989-03-28 23:57:32');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('49', 'Rosalyn', 'Witting', 'katherine51@shop.com', '1977-04-14 11:35:09', '2005-07-24 04:58:39');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('50', 'Edmond', 'Glover', 'verna.wilderman@shop.com', '1975-09-08 13:21:05', '1996-09-23 04:05:05');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('51', 'Ellsworth', 'Lang', 'ebba.nikolaus@shop.com', '1997-03-07 23:30:59', '1982-03-30 15:57:36');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('52', 'Lexi', 'Dickens', 'jensen.brakus@shop.com', '1987-01-23 23:06:21', '1991-12-20 21:22:50');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('53', 'Gideon', 'Larkin', 'qkiehn@shop.com', '1977-06-01 19:53:04', '1998-02-21 23:38:01');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('54', 'Henry', 'Ankunding', 'witting.hillard@shop.com', '2001-11-14 09:32:02', '1975-10-29 08:22:28');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('55', 'Paul', 'Stehr', 'hessel.camille@shop.com', '2016-07-30 07:57:15', '1997-09-02 07:35:56');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('56', 'Hassie', 'Watsica', 'roxanne.klein@shop.com', '2000-05-30 02:06:44', '1993-04-05 20:36:02');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('57', 'Kamille', 'Farrell', 'xaltenwerth@shop.com', '1980-11-08 23:48:14', '1997-05-19 15:23:21');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('58', 'Shanel', 'Bartell', 'dianna.osinski@shop.com', '2002-12-21 15:32:40', '1982-03-23 17:54:59');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('59', 'Derek', 'Thompson', 'asia97@shop.com', '1980-02-14 02:11:12', '2010-12-29 15:09:34');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('60', 'Andres', 'Turner', 'dlueilwitz@shop.com', '1984-02-21 14:16:21', '2003-06-15 16:41:19');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('61', 'Haylie', 'Rath', 'wfritsch@shop.com', '2004-04-26 04:57:06', '1998-03-09 18:06:12');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('62', 'Dylan', 'Tillman', 'durgan.drew@shop.com', '1978-12-15 06:06:24', '2008-03-25 18:02:27');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('63', 'Joany', 'Lakin', 'walsh.maurice@shop.com', '2016-03-06 20:07:16', '2011-09-15 10:50:41');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('64', 'Brannon', 'Steuber', 'maggie.hayes@shop.com', '1997-11-09 02:03:01', '1977-08-17 21:50:32');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('65', 'Cordia', 'Leannon', 'lesley.lindgren@shop.com', '1975-04-12 04:39:50', '2002-05-13 07:48:12');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('66', 'Marley', 'Von', 'gkerluke@shop.com', '2008-07-17 09:18:15', '2008-04-02 19:52:09');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('67', 'Twila', 'Streich', 'rsmitham@shop.com', '1972-10-13 19:17:26', '2015-01-02 05:24:46');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('68', 'Dannie', 'Blick', 'ofeest@shop.com', '1976-01-23 14:03:31', '2003-03-22 06:16:39');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('69', 'Jamal', 'Schaden', 'jadyn.rowe@shop.com', '1986-10-29 08:43:36', '1989-03-18 19:33:44');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('70', 'Nicolette', 'Stoltenberg', 'alberta.ryan@shop.com', '1989-05-27 03:23:43', '1970-01-04 01:55:04');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('71', 'Hertha', 'Luettgen', 'harris.piper@shop.com', '1982-09-26 18:37:07', '1999-09-07 16:50:04');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('72', 'Melody', 'Renner', 'krippin@shop.com', '2014-08-29 03:01:47', '2014-10-22 01:39:45');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('73', 'Jordon', 'Keeling', 'franco54@shop.com', '1993-07-15 09:32:02', '2008-12-31 11:11:34');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('74', 'Alexis', 'Hammes', 'brian42@shop.com', '2003-02-17 09:01:06', '1996-05-01 11:41:44');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('75', 'Hans', 'Roberts', 'hmayert@shop.com', '2007-09-29 12:37:37', '1972-06-30 04:01:52');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('76', 'Adam', 'O\'Conner', 'kallie.hermann@shop.com', '2003-07-25 10:08:43', '2006-11-19 20:06:28');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('77', 'Estella', 'Shanahan', 'kennedi.hauck@shop.com', '1985-11-30 08:17:02', '1979-08-04 18:03:11');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('78', 'Maude', 'Stiedemann', 'johns.amani@shop.com', '2008-12-21 21:14:30', '2005-04-03 11:33:59');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('79', 'Osborne', 'Kemmer', 'mathilde.quigley@shop.com', '2002-11-21 23:38:50', '2014-06-07 21:43:08');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('80', 'Sebastian', 'Hauck', 'tillman.alanna@shop.com', '1982-12-29 03:05:59', '1992-05-08 11:21:13');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('81', 'Annie', 'Fay', 'mayert.cathrine@shop.com', '2011-02-02 00:51:56', '2016-11-24 08:59:51');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('82', 'Ellen', 'Keebler', 'violet09@shop.com', '1999-08-06 11:15:23', '2002-01-12 03:54:53');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('83', 'Hal', 'Hayes', 'jermey44@shop.com', '1975-04-27 04:11:50', '1986-10-31 23:33:03');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('84', 'Juvenal', 'Vandervort', 'ttillman@shop.com', '2005-04-27 23:43:04', '1999-05-24 21:25:35');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('85', 'Evalyn', 'Gerlach', 'hattie39@shop.com', '2001-12-20 08:56:35', '1995-05-20 14:58:44');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('86', 'Adrianna', 'Crist', 'jaida02@shop.com', '2018-01-30 05:00:46', '2016-10-10 19:29:05');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('87', 'Davin', 'Fritsch', 'zpouros@shop.com', '2003-09-17 03:30:40', '1991-01-19 01:12:57');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('88', 'Madilyn', 'Cartwright', 'mraz.marcia@shop.com', '2004-07-02 18:50:30', '1974-07-04 20:39:48');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('89', 'Bethany', 'Paucek', 'conroy.jonas@shop.com', '1973-10-03 06:44:21', '2018-07-17 23:01:11');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('90', 'Ladarius', 'Ondricka', 'candido05@shop.com', '1986-03-11 17:36:01', '1971-09-30 02:48:38');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('91', 'Roslyn', 'Cremin', 'parker.cecelia@shop.com', '1984-06-12 01:14:42', '1980-09-11 07:47:53');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('92', 'Abigayle', 'Botsford', 'wzulauf@shop.com', '1986-04-22 02:35:10', '2017-07-18 06:07:15');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('93', 'Cora', 'Hartmann', 'qcole@shop.com', '1978-08-15 22:50:34', '1976-06-02 03:52:32');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('94', 'Leanna', 'Robel', 'vanessa95@shop.com', '1975-06-06 17:37:55', '2019-02-13 22:16:16');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('95', 'Daija', 'Kulas', 'sammy15@shop.com', '1994-11-21 01:00:02', '2019-09-17 21:35:34');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('96', 'Kailey', 'Zboncak', 'ben18@shop.com', '2000-10-27 20:59:40', '2003-08-17 21:58:18');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('97', 'Ubaldo', 'Schmeler', 'nikki.lubowitz@shop.com', '1999-06-01 17:04:58', '1974-12-02 03:45:49');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('98', 'Clemmie', 'Doyle', 'micah42@shop.com', '2017-01-24 09:27:07', '2007-11-13 17:02:28');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('99', 'Dimitri', 'Beier', 'elenora.bode@shop.com', '1990-10-03 20:16:04', '1998-04-07 03:23:46');
INSERT INTO `customer_service` (`id`, `firstname`, `lastname`, `email`, `created_at`, `updated_at`) VALUES ('100', 'Destinee', 'Adams', 'acrona@shop.com', '1984-11-26 01:20:34', '1977-07-25 08:15:02');


#
# TABLE STRUCTURE FOR: messages
#

DROP TABLE IF EXISTS `messages`;

CREATE TABLE `messages` (
  `customer_id` int(10) unsigned NOT NULL,
  `customer_service_id` int(10) unsigned NOT NULL,
  `body` text COLLATE utf8_unicode_ci NOT NULL,
  `important` tinyint(1) DEFAULT NULL,
  `delivered` tinyint(1) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`customer_id`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (1, 100, 'Porro animi velit et et dolorem consequatur recusandae. Amet laboriosam qui nesciunt eos. Qui ea neque cumque aspernatur praesentium.', 0, 0, '1997-10-10 13:53:06');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (2, 87, 'Laborum officia deleniti quae in voluptatibus. Non qui consectetur omnis est deleniti nihil. Aut eligendi eos minus libero voluptas.', 0, 0, '2001-10-24 09:41:44');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (3, 6, 'Accusantium repellendus cupiditate velit nisi quia ratione. Quia nihil qui sunt non perspiciatis perferendis. Quia libero explicabo sed dolores blanditiis voluptas at. Eum reiciendis quia eligendi quaerat. Accusantium sunt voluptate eveniet quas perspiciatis nulla.', 1, 0, '2011-12-13 08:38:22');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (4, 67, 'Voluptatem eum quia optio aut. Occaecati architecto laboriosam odio odit accusantium. Quasi ut aliquam natus laborum quibusdam cumque.', 0, 1, '2004-03-12 03:05:01');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (5, 4, 'Quis occaecati eum est hic fuga eos. Harum qui fuga dolorem fugiat earum libero mollitia. Enim dolor suscipit dolores. Cupiditate delectus sed doloribus.', 0, 1, '1987-09-05 09:02:45');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (6, 89, 'Nobis ducimus sed est ipsum deserunt earum. Dolores sed eum repellendus illo et odit. A distinctio eveniet nulla quasi nulla et. Ut enim consequatur accusamus facilis.', 0, 0, '2017-03-05 02:05:17');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (7, 5, 'Quod nobis rerum libero dolorum omnis. Sed ut deserunt sed eum saepe.', 0, 0, '2005-08-26 14:24:28');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (8, 30, 'Qui deserunt doloribus nulla voluptas et est. Et quasi omnis animi nemo. Libero suscipit voluptatum distinctio id quaerat. Neque cupiditate enim non ex quasi.', 1, 0, '1997-12-11 14:16:37');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (9, 51, 'Consequatur amet ut rerum qui laudantium porro ducimus. Assumenda corrupti totam est molestias soluta enim enim. Quis ab sed rerum necessitatibus. Est cum ipsum tempora quas. Nisi recusandae perspiciatis corporis sapiente id iste mollitia fuga.', 0, 1, '1971-05-29 19:45:29');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (10, 38, 'Necessitatibus rerum rerum sunt. Id velit ut fugit ut in quia dolorem. Hic a illum et modi.', 1, 1, '1982-05-04 06:52:26');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (11, 78, 'Doloribus placeat nulla sed ullam. Hic eaque autem optio voluptas. Qui magni deserunt et sed delectus. Quia repellendus sunt animi aut perferendis error.', 1, 0, '1976-05-11 00:11:35');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (12, 17, 'Sunt voluptatem rerum dolore saepe qui perferendis. Sapiente et suscipit et consequatur. Eum expedita accusantium ut a. Rerum aut necessitatibus voluptas aperiam iure.', 1, 0, '2006-02-02 19:23:10');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (13, 81, 'Fugiat nostrum corporis iure error dolores maiores. Consequatur aliquam ut ea voluptatem commodi.', 0, 1, '1972-01-12 16:40:10');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (14, 32, 'Quisquam dicta cupiditate soluta modi eveniet quia voluptatum. Incidunt iusto voluptatibus numquam doloribus hic ea distinctio. Molestiae amet ratione excepturi perspiciatis similique dolores. Ex magni praesentium optio eum corporis. Voluptate assumenda molestiae commodi quos eius.', 0, 1, '1974-10-25 13:09:51');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (15, 39, 'Molestiae qui ipsa natus repellendus. Qui laborum quo culpa hic ut. Et autem consequuntur similique ratione. Fugiat voluptatem a dolores.', 0, 0, '1978-08-22 03:42:04');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (16, 92, 'Dolores sit aut et qui in. Ut aut suscipit ut cumque id sunt. Id ducimus repellendus qui corrupti voluptatem quis eum. Quam nesciunt ipsa quasi dolor voluptas doloribus minima.', 1, 1, '1974-11-10 13:31:24');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (17, 65, 'Esse qui voluptates veniam inventore. Temporibus odit sit porro. Reiciendis delectus facere molestiae sed facilis repudiandae non. Tempore numquam nihil ab molestiae perspiciatis.', 0, 0, '2017-01-26 10:18:33');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (18, 73, 'Consequuntur rerum omnis et dolore vel. Animi magnam qui iure autem quod nobis. Neque eveniet quae eius qui fugit. Temporibus aut aliquid sit cum.', 0, 0, '2004-12-13 17:24:35');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (19, 66, 'Facere impedit et rerum sunt iure. Rerum vero ipsum consequuntur facere quia et et. Quaerat id maiores eum debitis perferendis.', 1, 1, '1988-04-19 21:10:08');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (20, 3, 'Sed at et repellat enim illo. Eligendi illum qui aspernatur occaecati et omnis delectus. Omnis dolorem facere distinctio impedit hic.', 0, 0, '2017-03-22 00:40:15');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (21, 25, 'Vitae qui assumenda laborum cupiditate fugit nostrum eius. Quo ducimus aperiam deleniti est. Et molestias ut consequatur aut eligendi ut quos a. At ex tenetur unde quo.', 0, 0, '1985-11-11 20:12:58');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (22, 74, 'Sed sit et molestiae. Asperiores ad animi voluptas et maxime. Harum nam in facere libero et sed. Aliquam repellendus sunt voluptas mollitia.', 0, 0, '2011-08-21 00:03:17');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (23, 53, 'Officia dolorum quia quisquam natus mollitia. Quas voluptatum veritatis consequuntur qui. Illum est enim fuga laboriosam.', 1, 0, '1979-12-19 17:04:37');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (24, 14, 'Aut ut distinctio doloribus. Enim modi est nostrum qui. Minus repellat itaque et sed voluptatum qui sed.', 1, 1, '1988-05-27 08:35:58');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (25, 90, 'Accusantium molestias totam assumenda officiis quo itaque. Quisquam quasi ut omnis est laudantium natus. Inventore nobis commodi aperiam ducimus ad.', 0, 0, '1992-09-07 05:20:15');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (26, 71, 'Autem et aperiam mollitia voluptas quia odio est magnam. Culpa vitae reprehenderit dolorem beatae. Eum voluptates quas labore facilis provident ut.', 0, 1, '1983-09-06 10:58:02');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (27, 21, 'Est id non neque aspernatur iure debitis alias. Itaque nemo nesciunt sit ut nemo. Accusantium ut perspiciatis dolore voluptates unde vel exercitationem voluptatem. Aliquam sed vitae qui occaecati qui modi laudantium.', 1, 1, '2002-06-25 12:07:43');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (28, 36, 'Qui est consequuntur veniam est harum ipsum. Dolor in maxime asperiores perferendis iusto at. Cupiditate est et voluptates voluptatibus provident labore possimus. Placeat quidem vitae eum laboriosam accusamus qui.', 1, 1, '2000-10-19 20:25:21');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (29, 50, 'Blanditiis quis cupiditate autem incidunt dolorem magnam. Placeat et omnis dolore ut. In beatae qui voluptatem deserunt similique nam iure. Impedit inventore assumenda ut.', 0, 0, '2015-09-09 09:03:08');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (30, 56, 'Vitae perferendis quia non adipisci qui quisquam minus similique. Nihil illum perspiciatis amet molestiae. Quam voluptas dolore vero occaecati.', 0, 1, '1970-05-08 10:34:04');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (31, 43, 'Vel architecto hic quaerat aut ipsa et quia commodi. Alias nesciunt iure at excepturi temporibus facilis debitis. Non beatae voluptates unde mollitia.', 0, 1, '1996-08-21 19:35:30');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (32, 91, 'Aliquam iste adipisci voluptas modi repellat. Aliquam minus molestiae quasi sunt iusto ullam consequatur. Saepe et voluptatem tenetur eaque accusamus.', 0, 0, '1999-09-15 15:38:29');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (33, 96, 'Quibusdam alias odit consequuntur consequatur impedit ut autem. Nisi dignissimos doloribus officiis consequatur ipsam. Excepturi illo ut in est.', 0, 0, '1973-03-01 13:07:09');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (34, 34, 'Explicabo quas officiis dolor laboriosam aut id aliquid quo. Labore error et tenetur similique quibusdam. Rerum aut qui alias ad eveniet et.', 0, 0, '2003-01-07 04:52:30');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (35, 85, 'Qui vero optio sed sequi sit beatae enim. Dolor a hic recusandae placeat ut. Quidem ipsa rerum alias non et consequatur.', 0, 0, '1973-06-15 00:14:35');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (36, 12, 'Quibusdam ducimus ad nisi repudiandae. Vel ex dolores et. Laboriosam porro sint est cumque reiciendis magnam et. Laboriosam sequi officiis rerum ut. Quia sint ipsum debitis.', 0, 1, '1994-09-26 08:38:49');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (37, 62, 'Quo ipsum rerum harum et. Veritatis optio dolor rerum illo amet ullam est. Quod quod reiciendis non non nesciunt eligendi similique.', 0, 0, '1971-06-05 18:24:15');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (38, 52, 'Et reprehenderit quia quae modi illo. Cum dolor quo culpa. Dicta qui quam non ut quam exercitationem quos numquam.', 0, 1, '2006-01-02 14:45:54');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (39, 40, 'Delectus iure ut accusamus quaerat dicta dolor. Adipisci laboriosam ut et autem esse error aut. Sint provident consequatur velit ut magni. Enim id deserunt nemo accusantium.', 0, 0, '1972-03-09 07:28:11');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (40, 59, 'Sint et quis sapiente nulla ut. Corrupti ut qui ea odio id necessitatibus. Ab ut iure culpa recusandae aut voluptate non.', 1, 1, '2017-10-04 05:41:40');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (41, 86, 'Ut doloribus velit minus ex. Perferendis alias qui nemo ducimus quo et illum omnis. Deleniti sunt ut tempora impedit cumque.', 1, 1, '2007-04-22 08:37:46');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (42, 20, 'Voluptatem eum qui amet odit dolorum. Architecto enim illum ea quo necessitatibus quia. Sit quia aut earum quaerat. Autem qui et impedit at quas sed mollitia.', 1, 0, '1984-01-23 08:40:43');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (43, 61, 'Eum ea error maxime est voluptas. Placeat laboriosam pariatur debitis eaque maxime. Similique sed aperiam quia sequi consequatur.', 0, 1, '1997-07-08 18:11:00');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (44, 72, 'Laborum eveniet rerum delectus provident. Excepturi sed eveniet est distinctio tempore pariatur et. Repudiandae nemo eos exercitationem est maxime. Quis magni quod non dicta in minus.', 1, 1, '2008-10-19 14:32:14');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (45, 80, 'Incidunt officia repellat consequatur sapiente. Consectetur et laboriosam illo sit eaque laborum dolore. Aliquam qui dolorem fugiat voluptatem.', 1, 0, '1992-06-29 23:06:24');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (46, 16, 'Perferendis dolorum repellat dignissimos id similique deserunt earum. Fuga adipisci et quis laudantium vero eligendi. Occaecati deleniti aliquid nihil quaerat hic ipsa illum et.', 1, 1, '2015-06-16 03:06:59');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (47, 45, 'Error veniam repellat dolores itaque. Eveniet corporis autem quo ut atque sit deleniti. Itaque error fuga error fuga. Voluptatem illo ex dolor sunt fugit.', 1, 0, '2007-05-04 10:51:08');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (48, 23, 'Eligendi voluptatum et aut ut fuga quod nihil. Aperiam amet rerum aliquid molestiae in ducimus. Sit possimus repellendus nihil dolores dolorum harum. Velit id sapiente molestiae commodi rerum perferendis officia.', 1, 1, '1977-12-03 15:58:28');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (49, 82, 'Quo saepe quod possimus minus non. Et laborum explicabo aut voluptas. Non eum eos est dolor eaque. Amet voluptate ducimus quia dolore maxime.', 1, 0, '1975-03-07 05:35:37');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (50, 28, 'Quia nemo aut excepturi aliquam eum et. Asperiores velit quaerat itaque tempore. Rem consequatur magnam doloremque et aut.', 0, 0, '1977-05-09 00:59:54');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (51, 64, 'Quis eos sequi labore quod et explicabo qui. Rem saepe quam voluptatem. Aut sit dolorum aut recusandae est enim.', 0, 0, '1989-02-22 22:30:14');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (52, 15, 'Vel ut ut quibusdam id. Et enim reprehenderit tenetur debitis accusantium. Dolorem ea dolorum minima sed. Nemo labore id repellat sit.', 1, 0, '1992-04-25 01:43:26');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (53, 31, 'Possimus dolor nulla ex nulla temporibus dignissimos eos. Voluptas architecto rem laboriosam consequuntur.', 1, 1, '1998-01-15 20:15:23');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (54, 2, 'Ut praesentium minima et. Eos et sunt animi eveniet. Aut a quasi qui ut.', 1, 1, '2014-05-17 11:14:33');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (55, 55, 'Aut culpa aliquam nesciunt quia. Est nulla voluptatem magni aut illo deleniti. Unde eius maxime aut reiciendis omnis ab error. Inventore accusamus autem autem et sed modi ad.', 0, 0, '2004-10-13 12:18:44');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (56, 42, 'Fugit similique sed architecto perspiciatis occaecati. Deleniti voluptatem nihil aspernatur consequatur quae et sit. Ea explicabo corrupti quisquam animi earum beatae. Dignissimos qui omnis id officia quaerat.', 0, 1, '1986-10-16 18:06:40');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (57, 13, 'In quam autem sit ab quia. Praesentium nobis accusamus et sapiente eius non aut doloremque. Id atque unde dolores voluptatem aliquid aut autem.', 1, 1, '2015-09-15 13:19:00');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (58, 41, 'Saepe sit rem in architecto. Asperiores est quo inventore id ullam. Natus voluptates architecto eum blanditiis et eligendi cum ullam. Porro sed nemo nostrum voluptate qui sapiente.', 1, 0, '1970-03-25 10:42:09');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (59, 35, 'Repudiandae omnis pariatur sed consectetur et. Tenetur sunt debitis dolores dolor qui officiis. Qui dignissimos nemo repudiandae illum adipisci molestiae.', 1, 1, '1975-04-12 12:12:35');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (60, 24, 'Excepturi eos et et deleniti. Voluptate molestiae blanditiis et cumque et ipsam aliquid. Aliquam et facere ducimus velit. Enim et eos est ad enim.', 1, 0, '1983-03-24 10:17:06');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (61, 8, 'Fugit aspernatur accusantium animi. Quaerat ut enim sapiente est distinctio omnis voluptas. Qui magni culpa alias reiciendis earum et. Quaerat quis ducimus aut.', 1, 1, '2012-04-19 11:57:29');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (62, 18, 'Modi cupiditate in rerum eius qui quas amet reiciendis. Aut placeat at libero eius. Suscipit qui id et eius illum nam repudiandae. Animi magni aperiam rem incidunt beatae.', 0, 1, '1972-07-23 03:56:15');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (63, 97, 'Eum rem dolore molestias culpa ut. Dolor sit eum at iusto distinctio occaecati. Veritatis possimus dolor eligendi porro minima.', 0, 0, '1978-11-12 17:54:02');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (64, 99, 'Et ipsa laboriosam porro quam tenetur aut. Et est exercitationem sapiente omnis. Eos consequuntur illum iste sequi id ut qui.', 0, 1, '2003-07-01 02:03:31');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (65, 69, 'Et quisquam ut et. Earum sed aperiam deleniti nobis commodi consectetur. Ad dolores labore possimus est labore pariatur. Fugit voluptate at qui.', 1, 1, '2006-12-30 08:59:59');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (66, 58, 'Quibusdam sunt quo dolor non. Sed cupiditate quo nisi et voluptatum. Nihil maiores est facere reiciendis asperiores veritatis voluptatem.', 0, 1, '1994-02-21 21:30:39');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (67, 9, 'Nemo ad et reprehenderit dolor quod quas placeat. Sunt et delectus exercitationem amet. Rem repellat aut qui rerum.', 1, 0, '2006-12-17 20:07:49');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (68, 68, 'Rerum voluptas velit voluptatum ab. Dolores necessitatibus libero quibusdam vero sit. Qui et eum eligendi provident consequuntur repellendus qui ipsam.', 1, 0, '1970-05-24 04:11:09');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (69, 70, 'Consequatur tenetur et quis odit et. Ratione architecto voluptatem unde porro ea voluptas earum magnam. Officiis ducimus vel sed qui dicta totam dolorem.', 0, 0, '1996-07-18 07:12:36');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (70, 79, 'At quia doloribus odio quo voluptatem. Nihil id quis qui et dolorum blanditiis suscipit.', 1, 0, '1989-04-28 01:46:23');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (71, 84, 'Ex dolorem accusantium id molestias recusandae dolor voluptatem. Ipsam accusantium consequuntur quam adipisci. Praesentium ad sed animi illo recusandae occaecati. Cupiditate fugiat sed odit placeat voluptatem provident iste.', 0, 0, '1985-10-17 23:16:48');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (72, 83, 'Sequi aut sed laboriosam facere eveniet provident in. Dolores maxime veritatis aut cupiditate nulla laboriosam eaque voluptatum. Repudiandae vel voluptas quaerat omnis consequatur. Vel perspiciatis fugit voluptas mollitia dolorem aliquam. Doloribus ducimus dolorem quod mollitia.', 0, 1, '1977-04-04 14:43:09');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (73, 47, 'Qui dolor architecto sit minus dolor. Neque qui aut corporis et suscipit suscipit omnis. Autem doloremque voluptate laborum architecto optio placeat et.', 1, 1, '1998-11-28 19:00:12');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (74, 1, 'Et reiciendis aut maiores dolorem at vel possimus. Eum provident debitis voluptas non adipisci aut sint. Rerum sunt excepturi reiciendis commodi quis. Eum dicta sint aperiam dolores quasi molestias.', 0, 0, '2017-07-15 08:31:01');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (75, 27, 'Optio suscipit aut dolorem et necessitatibus non delectus doloremque. Quia modi dolores debitis cupiditate ipsum aut eveniet. Quos consequatur qui alias et et reprehenderit. Provident ex et et voluptatem est.', 0, 1, '1973-01-05 05:10:47');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (76, 22, 'Ea error nihil repellat architecto ipsa quidem. Quibusdam aut ab ut iure sint facere pariatur. Dolores reprehenderit optio id consequatur sint nemo et. Minima sit est quia nam ex.', 1, 0, '1984-12-10 00:49:34');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (77, 93, 'Laborum ex deserunt libero sit nemo ab ea. Rerum molestiae et harum qui doloremque. Et non omnis omnis fugiat quidem harum delectus.', 1, 1, '1989-02-12 10:41:06');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (78, 7, 'Cumque maxime quia amet. Nemo voluptate labore sequi rerum voluptatum. Illo aut velit ut accusantium.', 1, 0, '1983-09-11 23:58:30');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (79, 29, 'Quae nobis reprehenderit molestiae sed omnis consequatur possimus. Ad at et perferendis omnis velit accusantium. Sunt deleniti suscipit sed.', 1, 1, '1991-08-10 10:11:18');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (80, 63, 'Et nihil et quam nostrum dolores. Sapiente molestiae quis et nulla vel consequatur aut. Eos est error molestias voluptatem aliquid inventore est perferendis.', 1, 0, '1976-01-10 07:02:02');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (81, 98, 'Nihil placeat fugit velit qui repellat. Omnis officiis et nostrum nesciunt. Eum ullam vel sed ex.', 0, 0, '1977-11-18 08:26:22');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (82, 19, 'Minus similique neque quia quibusdam dolorum. Voluptatem ipsa aut molestias libero. Quam perspiciatis qui vel laudantium eius ut officiis.', 1, 1, '2011-03-29 23:00:30');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (83, 48, 'Eos nulla nesciunt omnis mollitia aut ab. Qui suscipit neque dolore soluta impedit. Ratione temporibus quos inventore eum aut inventore blanditiis. Repudiandae ex et ipsum.', 0, 1, '1987-12-23 14:00:13');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (84, 49, 'Aut veritatis illo facere est tempore aliquam qui molestias. A delectus beatae quam. Ut voluptatibus molestiae tempore est consequatur facilis.', 1, 1, '2001-04-21 17:40:29');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (85, 94, 'Neque expedita et minus incidunt et repellat quos est. Ex voluptatum reprehenderit ut consequatur exercitationem praesentium dicta. Dolores consequatur molestiae possimus odit accusamus pariatur repudiandae. Consequatur veritatis autem ut sit voluptatum.', 0, 0, '1994-12-08 15:41:54');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (86, 75, 'Fugiat alias doloremque vitae unde aut corporis eos officiis. Nostrum laborum aperiam alias nemo reprehenderit dolor labore. Eaque aliquam itaque dolorem veritatis impedit asperiores.', 1, 0, '1992-11-12 18:17:38');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (87, 33, 'Explicabo cupiditate quaerat labore est quia vero maiores quidem. Cumque perferendis nulla quia reprehenderit. Aut exercitationem voluptatem est quod.', 0, 0, '1999-11-23 06:19:22');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (88, 88, 'Qui aspernatur alias quia. Et enim adipisci culpa sit ipsa vero. Et voluptatem ipsum ipsum provident libero. Ut qui repudiandae eum tempore perferendis.', 1, 1, '2000-12-24 07:47:45');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (89, 60, 'Quis voluptas architecto reiciendis exercitationem odit. Molestias repudiandae vel modi debitis sed. Deleniti facere quo fugit architecto.', 1, 1, '1988-12-26 07:09:09');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (90, 10, 'Qui tempore voluptatem neque a. Maiores fuga quas qui. Illum ab aut occaecati id et aut vel. Nam incidunt omnis quam maiores laudantium.', 0, 1, '1977-01-09 06:52:56');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (91, 37, 'Voluptate optio perspiciatis doloremque ut maiores. Nihil molestiae et labore porro consectetur. Consequatur similique magnam sit ut ducimus ut. Repellendus maiores tenetur voluptatem quos.', 1, 1, '2014-08-15 19:28:48');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (92, 95, 'Et ut ullam consequatur magnam. Quaerat illo aut itaque tenetur reiciendis sit rerum doloremque.', 0, 1, '2013-04-18 07:46:30');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (93, 76, 'Et fugit nam nam qui amet voluptates velit. Non dolor necessitatibus quam fugit nisi eum. Quaerat id nihil magnam laudantium.', 1, 0, '1997-03-28 09:54:27');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (94, 44, 'Et mollitia dolor accusantium nisi magni dolorem. Ipsum accusamus qui quam omnis numquam. Nesciunt omnis minus debitis et rerum placeat.', 1, 1, '2012-10-05 13:01:46');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (95, 54, 'Est iure laboriosam voluptatem occaecati blanditiis. Commodi sed quia labore consequatur veritatis et dignissimos corrupti. Dolore cumque et quia voluptatem est architecto nostrum. Possimus dolores maiores quia corrupti et.', 1, 0, '1992-05-25 07:33:56');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (96, 57, 'Nobis laudantium quo sit. Optio corrupti architecto quis vero. Suscipit at quibusdam in aut quibusdam est quidem omnis.', 1, 1, '1995-09-29 05:03:50');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (97, 46, 'Qui ut ut fugit officiis et. Fugiat ut natus laboriosam expedita. Tempore consequuntur quibusdam aspernatur reiciendis et rerum. Placeat voluptatibus velit ex.', 0, 1, '2000-07-26 11:40:26');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (98, 11, 'Vel beatae aspernatur odio saepe et. Quod ad eligendi culpa culpa autem est provident. Aspernatur ea est nemo hic. Nobis ratione sit corporis sed iusto labore expedita.', 0, 0, '1982-12-26 15:48:58');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (99, 77, 'Similique architecto voluptate labore autem doloremque expedita error. Aut provident et cupiditate nam porro. Enim occaecati ab deserunt aut soluta.', 0, 1, '1980-09-20 12:32:22');
INSERT INTO `messages` (`customer_id`, `customer_service_id`, `body`, `important`, `delivered`, `created_at`) VALUES (100, 26, 'Autem sunt maxime corrupti ad magnam cum illo. Laudantium qui id sint sunt quibusdam rerum quisquam. Quia est vel voluptatem dolorem.', 1, 0, '2004-07-24 12:02:15');


